import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        
        {children}
        <footer className="text-center">&copy; TC - Snack List - Module 4</footer>
      </body>
    </html>
  );
}
